# Generated by Django 4.1.3 on 2024-12-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_id', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('src', models.CharField(max_length=100)),
                ('dst', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('created', models.BigIntegerField()),
                ('updated', models.BigIntegerField()),
                ('json_data', models.JSONField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
