# Generated by Django 4.1.3 on 2024-12-27 09:24

import alerts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='status',
            field=models.CharField(default='open', max_length=5),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='alert_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='created',
            field=models.BigIntegerField(default=1735291453),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='severity',
            field=models.CharField(max_length=100, validators=[alerts.models.validate_severity]),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='updated',
            field=models.BigIntegerField(default=1735291453),
        ),
    ]
