# Generated by Django 4.1.3 on 2025-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alerts_status_alter_alerts_alert_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='short_description',
            field=models.CharField(default='*', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerts',
            name='created',
            field=models.BigIntegerField(default=1736241118),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='updated',
            field=models.BigIntegerField(default=1736241118),
        ),
    ]
