# Generated by Django 5.1.4 on 2025-01-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alerts_created_alter_alerts_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='created',
            field=models.BigIntegerField(default=1736415596),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='updated',
            field=models.BigIntegerField(default=1736415596),
        ),
        migrations.AlterField(
            model_name='iamroles',
            name='created',
            field=models.BigIntegerField(default=1736415596),
        ),
        migrations.AlterField(
            model_name='iamroles',
            name='updated',
            field=models.BigIntegerField(default=1736415596),
        ),
        migrations.AlterField(
            model_name='iamusers',
            name='created',
            field=models.BigIntegerField(default=1736415596),
        ),
        migrations.AlterField(
            model_name='iamusers',
            name='updated',
            field=models.BigIntegerField(default=1736415596),
        ),
    ]
